# -*- coding: utf-8 -*-
"""Copy of chuyen_de_loc_cong_tac.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GBhXmj7bskvFwfha0UulVdC0Of-_JWq8
"""

import numpy as np
import pandas as pd
import scipy.sparse
from scipy.spatial.distance import correlation

data=pd.read_csv('./data_collaborative_1.csv')
userIds=data.userId

data.loc[0:100,['userId']]
data=pd.DataFrame.sort_values(data,['userId','itemId'],ascending=[0,1])

userItemRatingMatrix=pd.pivot_table(data, values='rating',
                                    index=['userId'], columns=['itemId'], dropna=False)

userItemvisitMatrix=pd.pivot_table(data, values='isvisited',
                                    index=['userId'], columns=['itemId'])
userItemIsNotActive=pd.pivot_table(data, values='isNotActive',
                                    index=['userId'], columns=['itemId'])


def similarity(user1,user2):
    try:
        if (not np.isnan(user2).all()) and (not np.isnan(user1).all()):
            user1=np.array(user1)-np.nanmean(user1)
            user2=np.array(user2)-np.nanmean(user2)
            commonItemIds=[i for i in range(len(user1)) if user1[i]>0 and user2[i]>0]
            if len(commonItemIds)!=0:
                user1=np.array([user1[i] for i in commonItemIds])
                user2=np.array([user2[i] for i in commonItemIds])
                return correlation(user1,user2)
        return 0
    except ZeroDivisionError:
        print("You can't divide by zero!")

def nearestNeighbourRatings(activeUser,K):
    try:
        similarityMatrix=pd.DataFrame(index=userItemRatingMatrix.index,columns=['Similarity'])
        for i in userItemRatingMatrix.index:
            similarityMatrix.loc[i]=similarity(userItemRatingMatrix.loc[activeUser],userItemRatingMatrix.loc[i])
        similarityMatrix=pd.DataFrame.sort_values(similarityMatrix,['Similarity'],ascending=[0])
        nearestNeighbours=similarityMatrix[:K]
        neighbourItemRatings=userItemRatingMatrix.loc[nearestNeighbours.index]
        predictItemRating=pd.DataFrame(index=userItemRatingMatrix.columns, columns=['Rating'])
        for i in userItemRatingMatrix.columns:
            predictedRating=np.nanmean(userItemRatingMatrix.loc[activeUser])
            for j in neighbourItemRatings.index:
                if userItemRatingMatrix.loc[j,i]>0:
                   predictedRating += (userItemRatingMatrix.loc[j,i]-np.nanmean(userItemRatingMatrix.loc[j]))*nearestNeighbours.loc[j,'Similarity']
                predictItemRating.loc[i,'Rating']=predictedRating
    except ZeroDivisionError:
        print("You can't divide by zero!")            
    return predictItemRating

def topNRecommendations(activeUser,N):
    if(activeUser not in np.array(userIds)):
        return None
    try:
        predictItemRating=nearestNeighbourRatings(activeUser,11)
        placeAlreadyWatched_1=list(userItemRatingMatrix.loc[activeUser]
                              .loc[userItemRatingMatrix.loc[activeUser]>0].index)
        placeAlreadyWatched_2=list(userItemvisitMatrix.loc[activeUser]
                              .loc[userItemvisitMatrix.loc[activeUser]>0].index)
        placeDisable=list(userItemIsNotActive.loc[activeUser]
                              .loc[userItemIsNotActive.loc[activeUser]>0].index)
        placeAlreadyWatched=placeAlreadyWatched_1+placeAlreadyWatched_2+placeDisable
        placeAlreadyWatched=set(placeAlreadyWatched)
        predictItemRating=predictItemRating.drop(placeAlreadyWatched)
        topRecommendations=pd.DataFrame.sort_values(predictItemRating,
                                                ['Rating'],ascending=[0])[:N]
        topRecommendationTitles=(data.loc[data.itemId.isin(topRecommendations.index)])
        topRecommendation=set(topRecommendationTitles.itemId)
    except ZeroDivisionError:
        print("You can't divide by zero!")
    return list(topRecommendation)
#khi loại bỏ item,chỉ cần gán nhãn cho user đang xét đánh giá item đó là số >0 sẽ đảm bảo ko gợi ý sản phẩm đó
#khi thêm sản phẩm,thêm vào bình thường.
#các người dùng chưa đánh giá sản phẩm nào thì gán rate đó là  0